- name: Welcome to ProntoA
  hosts: all
  tasks:
    - name: Install the latest version of ProntoA
      ansible.builtin.yum:
        name: firewalld
        state: latest
      become: true

    - name: Start service firewalld, if not started
      ansible.builtin.service:
        name: firewalld
        state: started
      become: true

    - name: Opend Port 
      shell: sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp 
      become: true

    - name: Opend Port 
      shell: sudo firewall-cmd --reload
      become: true
