- name: Starting to ProntoA
  hosts: all
  tasks:
    - name: Copy file with owner and permissions
      file:
        path: /home/jparks7/pa_metric_agent-1.0-2.el8.x86_64.rpm
        state: absent

    - name: Copy file with owner and permissions1
      ansible.builtin.copy: 
        src: /home/jparks7/pa_metric_agent-1.0-2.el8.x86_64.rpm
        dest: /home/jparks7/pa_metric_agent-1.0-2.el8.x86_64.rpm

    - name: Started rpm files
      ansible.builtin.dnf:
        name: pa_metric_agent
        state: absent
      #become: True
      ignore_errors: True

    - name: Started rpm files
      ansible.builtin.dnf:
        name: /home/jparks7/pa_metric_agent-1.0-2.el8.x86_64.rpm
        state: present
        disable_gpg_check: yes

    - name: Modified hostname
      template:
        src: /home/jparks7/pa_metric_agent.cfg.j2
        dest: /etc/prontoa/pa_metric_agent.cfg
        force: yes
          #      become: True

    - name: Started angent shell
      service: 
        name: pa_metric_agent
        state: started
